name: "Build And Publish Release"
on:
  push:
    branches:
      - "github-action-ci"
#    tags:
#      - "v*-SNAPSHOT"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9

      - name: List Files
        run: ls

      - name: Execute Gradle build
        run: gradle shadowJar
        env:
          PRIVATE_REPO_USERNAME: ${{ secrets.PRIVATE_REPO_USERNAME }}
          PRIVATE_REPO_PASSWORD: ${{ secrets.PRIVATE_REPO_PASSWORD }}
