name: Test Discord

on:
  push:
    branches:
      - "discord-test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{\n  \"content\": null,\n  \"embeds\": [\n    {\n      \"title\": \"Wonderland UHC 已發布更新\",\n      \"color\": 42839,\n      \"fields\": [\n        {\n          \"name\": \"版本\",\n          \"value\": \"1.0.0\"\n        },\n        {\n          \"name\": \"更新內容\",\n          \"value\": \"- 這些還有那些\\n- 這些還有那些\\n- 這些還有那些\\n- 這些還有那些\\n- 這些還有那些\"\n        },\n        {\n          \"name\": \"載點\",\n          \"value\": \"https://github.com/MCWonderland/WonderlandUHC/releases/tag/1.0.3-SNAPSHOT\"\n        }\n      ]\n    }\n  ],\n  \"username\": \"Github\",\n  \"avatar_url\": \"https://user-images.githubusercontent.com/41278925/184468277-25183ff3-07bd-4d61-9792-0045d36a0fcd.png\",\n  \"attachments\": []\n}]'
        uses: Ilshidur/action-discord@master