name: Test Discord

on:
  push:
    branches:
      - "discord-test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"Wonderland UHC 已發布更新","color":42839,"fields":[{"name":"版本","value":"1.0.0"},{"name":"更新內容","value":"- 這些還有那些\n- 這些還有那些\n- 這些還有那些\n- 這些還有那些\n- 這些還有那些"},{"name":"載點","value":"https://github.com/MCWonderland/WonderlandUHC/releases/tag/1.0.3-SNAPSHOT"}]}]'
        uses: Ilshidur/action-discord@master